### PR TITLE
Fix wrong use search

### PR DESCRIPTION
**Pull request by zhaihj**
### Problem Description:
 
UseDef findUse() return wrong path according to the order of soures.

Assume that we have ./ooc-math.use and ./source/sdk/math.use. When searching for math.use, the following code

    if(subPath getPath() endsWith?(fileName))

gives ooc-math.use instead of math.use because both of them have suffixes "math.use" but ooc-math is searched first. This will cause circle dependency problem.

### How to reproduce:
Compile ooc-kean with the lastest rock.

### Fix:

* Added getName() to extract filename from path.
* When getName() does not work well, it will return the first match of endWiths.

### CODE REVIEW

**Comment by fasterthanlime** [comment]
Tried to reproduce by building ooc-kean, but it's failing earlier with a redefinition of `abs`, which seems weird:

screen shot 2015-01-12 at 16 29 45

**Comment by fasterthanlime** [comment]
@zhaihj Can you please have a look at https://github.com/fasterthanlime/rock/commit/da917b29d9bf17b71a03a31f9390f46167aedbbe ? That should fix it.

You folks at cogneco don't like simple fixes or what? :)

**Comment by davidhesselbom** [comment]
Goodness, that's a big text size for a terminal. 4K?

**Comment by davidhesselbom** [comment]
Btw, just fixed the abs problem, which mysteriously appeared today.

**Comment by fasterthanlime** [comment]
@davidhesselbom Just a retina display :) (native resolution: 2880x1800).

About abs: I think it might be related to the stricter checks introduced in 80e0a098adb4a48fcb9df64cb198dbacc175f780

(Which, in retrospect, explains a0c178ccc4f32a8a56d3d353dd39aad3a006eed1). Imho type extensions should be able to redefine functions if they feel like it, although that might be too obscure. Hm.

**Comment by vendethiel** [comment]
Do you want to open ruby's biggest can of worms :)?

**Comment by fasterthanlime** [comment]
@vendethiel d'awwwwww good point let's not talk about open classes or monkey-patching or any of that scripting language nonsense.

(But, btw, type extensions in ooc are a lie — and completely bypass the vtable.)

**Comment by vendethiel** [comment]
Sorry, it's been a long time since I last looked at some rock, but I just think... It's a bad idea to add that :P.

**Comment by fasterthanlime** [comment]
Actually it's been a very long time since I've read some parts of rock. And when I read it now, I just want to burn it all. To the ground. And rewrite it all. But who's got the time for that :(

Cogneco when you're rich, hire me, I'll make ooc better I promise.

**Comment by vendethiel** [comment]
Would you have, in retrospect, liked better to make ooc a "google" language? (as I think you got an email from google or smth)

**Comment by fasterthanlime** [comment]
I did get an e-mail from Google about a job offer — but they send hundreds of those everyday, it was nothing serious / personal. And it wasn't ooc-related as far as I could tell.

I've used ooc professionally at official.fm, and I've written [another compiler](https://github.com/memoways/shin) at my current company, and I'm still today using ooc in [another project, with yet another language on top](http://lestac.net/blog/2015/weekly-update-1/) — so, you know, I'm still "in the game" somewhat, just not running around, giving conferences and whatnot.

**Comment by davidhesselbom** [comment]
@fasterthanlime, this is what we're using ooc for: http://techcrunch.com/2015/01/09/imint-wants-to-bring-real-time-video-stabilization-to-android/

**Comment by davidhesselbom** [comment]
Just, you know, in case you're curious.

**Comment by fasterthanlime** [comment]
@davidhesselbom that looks really cool :)

**Comment by vendethiel** [comment]
Alright - amazing. Did see that new compiler :).

**Comment by fasterthanlime** [comment]
@davidhesselbom well, you know, if you've got some extra funding, I wouldn't mind spending some time doing paid work to improve ooc.

I might have to look into... alternative solutions of a financial kind, for the near future. Oh well.

**Comment by davidhesselbom** [comment]
@fasterthanlime How much to fix #829? ;)

(seriously though, it's been fixed, I just haven't had time to make a pull request yet)

**Comment by zhaihj** [comment]
@fasterthanlime 
that commit works perferctly. I will close this pr...

**Comment by fasterthanlime** [comment]
Thanks for confirming @zhaihj !
